
server:
  port: 8382



executorPool:
  corePoolSize: 5
  maximumPoolSize: 300
  keepAliveTime: 60
  queueCapacity: 5

mapDB:
  partitions: 1
  filePath: C:/Users/liaoyuecai/Desktop/test/

netty:
  server:
    port: 1333

